runtime: nodejs20
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env: standard
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
entrypoint: npm run serve
env_variables:
  REACT_APP_BACKEND_URL: 'https://urlfetcherbe.nw.r.appspot.com'